### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by mepcotterell** [scalation/analytics#10]
Just in case others want to contribute to the project, I suggest the following workflow (after my latest pull request is accepted)...

Branches:

 * ```master```: latest stable release
 * ```develop```: latest stable development version
 * ```mepcotterell```: Michael's contributions
 * ```mvnural```: Mustafa's contribution

If anyone wants to contribute to the project, whether it be Michael and Mustafa or other people on GitHub, they need to create a pull request against ```develop```. Michael and Mustafa can independently or cooperatively accept pull requests into ```develop``` if they assess the pull request will be close to error-free (or based on relevant information). Every so often, we merge ```develop``` into ```master``` (and tag it) to create an official release.

**Comment by mvnural** [comment]
This makes sense. Please go ahead and implement this. I'll make necessary changes in my copy.
