### ISSUE TITLE
hasDistribution object property

### ISSUE THREAD

**Issue by mvnural** [scalation/analytics#14]
It says here http://stats.stackexchange.com/a/57285 that the regression models do not make any assumptions of the distributions of any variable.
Does the distributions of the variables matter in any way for choosing an optimal model? I wonder if having an object property *hasDistribution* with a domain *Variable* and range *Distribution* makes any sense.

**Comment by mepcotterell** [comment]
Regression models make an assumption about the distribution of a model's residual/error term. There are some assumptions made about the variables (e.g., their domain of discourse, the non-collinearity of samples, etc.).

**Comment by mepcotterell** [comment]
Something we might want to look into is whether or not the variables are "fixed effects" or "random effects."
