### ISSUE TITLE
Milestones and Deadlines

### ISSUE THREAD

**Issue by mepcotterell** [scalation/analytics#20]
Mustafa, can we formalize the requirements for the next project milestone and come up with projected dates for them? I have a rough idea of what needs to be done based on our discussions and your recent commits, but it might be good to plan it out so we don't duplicate any work. 

Also, when is the acceptance notice on the paper we submitted?

**Comment by mvnural** [comment]
This is a great idea. We should go ahead and do it. Would you like to have a meeting or continue discussion here?

The notification date is April 24th according to the website.

**Comment by mepcotterell** [comment]
We can discuss here.

**Comment by mvnural** [comment]
OK.

I've created a milestone March Sprint and will create tasks and add them to it. Please feel free to add your stuff too.
