### ISSUE TITLE
Create a model class

### ISSUE THREAD

**Issue by mvnural** [scalation/analytics#21]
A Model class should be created to represent a dataset. Should have methods for adding/deleting/modifying axioms (variables, objectProperties, etc.)

**Comment by mepcotterell** [comment]
I don't know much work it would be, but it might be a good idea to write an API for marshaling/unmarshalling between OWL API individuals and instances of convenience/model classes. This would suggest parity between our Scala API and the ontology itself. 

At the very least, I think we should do what you suggest. However, it needs to be done in such a way that makes our use of the OWL APIA transparent to the users of our API.
