### ISSUE TITLE
Integrate with Travis-CI 

### ISSUE THREAD

**Issue by mvnural** [scalation/analytics#22]
It would be nice to have an integration with a continuous integration service such as Travis-CI so that we can be sure we don't break anything when we do pull-requests. 

Can add more tests in the future but the consistency test is sufficient for now.

**Comment by mepcotterell** [comment]
I just set this up. Now when we commit to either ```master``` or ```develop``` Travis-CI will attempt to build the project. 

https://travis-ci.org/scalation/analytics
