### ISSUE TITLE
Add a Unit test to check if the VariableType case objects have one-to-one correspondence with the ontology

### ISSUE THREAD

**Issue by mvnural** [scalation/analytics#31]

**Comment by mepcotterell** [comment]
What would this involve?

**Comment by mvnural** [comment]
1. Retrieve all variable types from the Ontology using the structural reasoner into a set. ( Example is available in the ModelClassifierInferenceTest (ModelClassifier) 
2. Somehow obtain a set from the case classes
3. Check two sets against each other. (Case class ontologyID corresponds to the ID of the class in the ontology.

This is what comes into my mind immediately. There might be simpler way to do this

**Comment by mvnural** [comment]
Completed with 9eaf5d56226dbec966a10200d3455def5f6aea87
