### ISSUE TITLE
Scalation as a dependency

### ISSUE THREAD

**Issue by mvnural** [scalation/analytics#33]
What should we the correct way to add ScalaTion as a dependency? I do it on my computer via my IDE but the builds keep failing in Travis CI as ScalaTion is not recognized.

We need to find a way to do this. Any suggestions?

**Comment by mepcotterell** [comment]
I created a pull request against your branch that should fix the issue. However, It should be noted that the solution drastically increases the build time (since it has to download ScalaTion, compile, and publish it locally).

**Comment by mepcotterell** [comment]
Just checked Travis CI, and it looks like the fix works. You should go ahead and accept the pull request. I'll hold off on incorporating the change into ```develop```, since it will be incorporated the next time you make a pull request from ```mvnural``` against ```master```.

**Comment by mvnural** [comment]
Thanks! This looks cool. I'll check it out and let you know.
