### ISSUE TITLE
Example Dataset(s)?

### ISSUE THREAD

**Issue by mepcotterell** [scalation/analytics#40]
I think it would be a good idea to include at least one example dataset with the project. Perhaps we can have a top-level directory called ```examples``` or ```example-datasets``` that has one dataset? This way, if someone runs the project, they'll have something to play around with. What does everyone think?

**Comment by mvnural** [comment]
I thought about this too and planned to include our famous auto-mpg dataset but I was worried about licensing etc. 
Let's discuss about this further.

**Comment by mvnural** [comment]
Completed with 01981ad6d0ad877eda24b64789ad0a5e0aae329c
